spring:
  application:
    name: API-GATEWAY
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      ## routing par fich properties
      routes:
        #Routes for employee service
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/employees/**
#        #Routes for department service
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/departments/**
      # ex: localhost:9191/api/departments/IT001
      # routing programatically
      #discovery:
       # locator:
        #  enabled: true
          # ex: localhost:9191/department-service/api/departments/IT001
         # lower-case-service-id: true
# to see the routing

server:
  port: 9191
eureka:
  instance:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 0.1
logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'