spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: passer

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 0.1
logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'


#eureka:
#  instance:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
