spring:
  application:
    name: ORGANIZATION-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/organization_db
    username: root
    password: passer

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    compatibility-verifier:
      enabled: false
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoint:
#    health:
#      show-details: always
#
#resilience4j:
#  circuitbreaker:
#    instances:
#      EMPLOYEE-SERVICE:
#        registerHealthIndicator: true
#        failureRateThreshold: 50
#        minimumNumberOfCalls: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowSize: 10
#        slidingWindowType: COUNT_BASED
#  retry:
#    instances:
#      EMPLOYEE-SERVICE:
#        maxAttempts: 5
#        waitDuration: 1s
#  tracing:
#    sampling:
#      probability: 0.1
#logging:
#  pattern:
#    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
#
#
#
